### PR TITLE
Add support for match setting in pep257.

### PR DESCRIPTION
**Pull request by codito**
If a user specifies a match regex, pep257 is run on the file
only if it matches the match regex.

Documentation for match is available here: https://pep257.readthedocs.org/en/latest/usage.html

### CODE REVIEW

**Comment by Robpol86** [comment]
Wow sorry, forgot about this pr, my bad.

I feel this is out of scope for flake8-pep257. I let flake8 handle file discovery not pep257, I believe this is what's expected for flake8 extensions.

**Comment by codito** [comment]
The use case that motivated this PR was to disable only pep257 for test files.

I had tried to solve it with flake8 config first, there is one challenge: if we use an ignore files pattern in flake8 configuration, it ignores all the flake8 checks on those files. Is there another alternate way?

**Comment by Robpol86** [comment]
I think the "right" way is to uninstall plugins. Plugins add functionality to flake8. flake8 and its plugins should act as one monolithic thing with a single configuration file that treats all supported files the same. It's like trying to  disable some built-in pep8 errors for some files. It's not supported.

**Comment by codito** [comment]
Thanks for clarification!

**Pull request closed without merging**
